# Strimzi Kafka Cluster CRD
# https://strimzi.io/docs/operators/latest/deploying.html

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: pr-bot
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  # Kafka broker configuration
  kafka:
    version: 4.1.1

    # Listeners for client connections
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    # Kafka configuration
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1

  # Entity Operator for managing Topics and Users via CRD
  entityOperator:
    topicOperator: {}
    userOperator: {}
